# Generated by Django 5.0.3 on 2024-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_study', models.IntegerField(default=0)),
                ('num_course', models.IntegerField(default=0)),
                ('final_mark', models.IntegerField(default=0)),
            ],
        ),
    ]
