# Generated by Django 5.0.3 on 2024-03-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification_model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictMark',
        ),
    ]
